#pragma once

// Version information - centralized shared metadata
// Runtime values come from ProductMetadata.json via ProductMetadataService
// Executable-specific identity comes from ExecutableMetadata
// VERSIONINFO resources are auto-generated by Scripts/Generate-VersionInfo.ps1

// NOTE: These macros are deprecated and provided for backward compatibility only.
// New code should use ProductMetadataService::Get() and ExecutableMetadata APIs.

#define PRODUCT_VERSION_MAJOR 1
#define PRODUCT_VERSION_MINOR 0
#define PRODUCT_VERSION_PATCH 0
#define BUILD_NUMBER 1001

#define PRODUCT_VERSION_STRING "1.0.0.1001"
#define PRODUCT_NAME "WindEffects"
#define PRODUCT_DESCRIPTION "WindEffects Engine"
#define COMPANY_NAME "Udinmo, Inc."
#define COPYRIGHT_STRING "© 2026 Udinmo, Inc. All rights reserved."

#define ENGINE_GUID "A7B3C8D2-1E4F-4A5B-8C9D-0E1F2A3B4C5D"
#define ENGINE_PROVENANCE "WE-PD-2026"

// To get executable-specific metadata at runtime:
//   we::core::ProductMetadataService::Get().Initialize();
//   we::core::ExecutableMetadata::ConfigureAsEditor(); // or other role
//   auto identity = we::core::ProductMetadataService::Get().GetExecutableIdentity();

