#pragma once

#include "KindUI/Export.h"

namespace we::runtime::kindui {

enum class StyleRole {
    Window,
    Workspace,
    Toolbar,
    Panel,
    PanelHeader,
    Tab,
    TabActive,
    Button,
    ButtonHover,
    ButtonActive,
    ButtonPrimary,
    ButtonSecondary,
    ButtonGhost,
    ButtonDanger,
    ToolbarButton,
    IconButton,
    IconButtonHover,
    IconButtonPressed,
    NavigationButton,
    Input,
    SearchBox,
    StatusBar,
    MenuBar,
    MenuItem,
    DockTab,
    DockTabActive,
    Splitter,
    Separator,
    Popup,
    Tooltip,
    Modal,
    Gizmo,
    ContentBrowser,
    TextPrimary,
    TextSecondary,
    TextCaption,
    TextHint,
    TextDisabled,
    Card,
    CardHover,
    TableHeader,
    TableRow,
    TableRowHover,
    TableRowSelected,
    SectionHeader,
    PropertyRow,
    SidebarItem,
    SidebarItemActive,
    WindowHeader,
    Checkbox,
    ToggleSwitch,
    Scrollbar,
    TreeItem,
    TreeItemSelected,
};

} // namespace we::runtime::kindui
