#pragma once

#include "WindEffects/Editor/UI/Export.h"
#include "WindEffects/Editor/UI/Core/Types.h"

#include <cstdint>

namespace WindEffects::Editor::UI {

enum class ThemeToken : uint32_t {
    WindowBackground,
    WorkspaceBackground,
    ToolbarBackground,
    PanelBackground,
    HeaderBackground,
    ViewportBackground,
    FooterBackground,
    MenuBarBackground,
    TabBackground,
    PopupBackground,
    ContentBrowserBackground,
    PanelContentBackground,
    PanelToolbarBackground,
    PanelTabActiveBackground,
    PanelTabInactiveBackground,
    DockAreaBackground,

    BorderLight,
    BorderDark,
    BorderDefault,
    BorderFocus,
    Separator,

    HoverBackground,
    ActiveBackground,
    SelectedBackground,
    DisabledBackground,
    PressedBackground,

    TextPrimary,
    TextSecondary,
    TextDisabled,
    TextMuted,
    TextWindowLabel,

    IconPrimary,
    IconSecondary,
    IconAccent,

    IconDefault,
    IconHover,
    IconActive,
    IconDisabled,

    AccentPrimary,
    AccentHover,
    ActiveTabLine,
    SelectionHighlight,
    Success,
    Warning,
    ErrorForeground,
    LinkForeground,
    CodeForeground,

    InputBackground,
    SearchBoxBackground,
    SearchPlaceholder,

    ViewportToolbarBackground,
    StatusBarBackground,

    ButtonPrimaryBackground,
    ButtonPrimaryHover,
    ButtonPrimaryPressed,
    ButtonDangerBackground,
    ButtonDangerHover,
    ButtonDangerPressed,

    GizmoBackground,
    GizmoAxisX,
    GizmoAxisY,
    GizmoAxisZ,

    HighlightSubtle,
    ShadowSubtle,
    ShadowOverlay,
    ModalScrim,

    ContentBrowserHoverBackground,
    ContentBrowserFolderShadow,
    ContentBrowserFolderEdge,
    ContentBrowserFolderHighlight,
    ContentBrowserFolderTab,
    ContentBrowserFolderPrimary,
    ContentBrowserFolderBody,

    CloseButtonHover,
    DragGhostBackground,
    TooltipBackground,

    DialogBackground,

    ScrollbarTrack,
    ScrollbarThumb,
    ScrollbarThumbHover,

    PlayForeground,
    ShadowPopup,

    CornerRadiusSmall,
    CornerRadiusMedium,
    CornerRadiusLarge,
    WindowCornerRadius,

    TextSizeMenu,
    TextSizeToolbar,
    TextSizeTabs,
    TextSizeNormal,
    TextSizeProperty,
    TextSizeCaption,
    TextSizeWindow,
    TextSizeHeader,
    TextSizeBody,
    TextSizeSmall,
    TextSizeCategory,
    TextSizeTitle,

    BorderWidth,
    FocusRingWidth,

    PanelHeaderHeight,
    PanelTabHeight,
    PanelToolbarHeight,
    ListRowHeight,
    CategoryHeaderHeight,
    TitleBarHeight,
    HeaderControlHeight,
    WindowControlWidth,
    ToolbarHeight,
    SearchBoxHeight,
    IconButtonSize,
    ButtonHeight,
    NavigationButtonSize,
    IconSizeSearch,
    IconSizeToolbar,
    IconSizePrimary,
    IconSizeTree,
    IconSizeNavigation,
    IconButtonRadius,
    ButtonPaddingHorizontal,
    ButtonSpacing,
    ButtonGroupSpacing,
    ScrollbarWidth,

    Space1,
    Space2,
    Space3,
    Space4,
    Space5,
    Space6,

    HoverAnimationDamping,
    PressAnimationDamping,
    PressOffset,

    ShadowBlurSmall,
    ShadowBlurMedium,
    ShadowSpreadMedium,

    PaddingPanelLeft,
    PaddingPanelTop,
    PaddingPanelRight,
    PaddingPanelBottom,
    PaddingButtonLeft,
    PaddingButtonTop,
    PaddingButtonRight,
    PaddingButtonBottom,
};

enum class StyleRole {
    Window,
    Workspace,
    Toolbar,
    Panel,
    PanelHeader,
    Tab,
    TabActive,
    Button,
    ButtonHover,
    ButtonActive,
    ButtonPrimary,
    ButtonSecondary,
    ButtonGhost,
    ButtonDanger,
    ToolbarButton,
    IconButton,
    IconButtonHover,
    IconButtonPressed,
    NavigationButton,
    Input,
    SearchBox,
    StatusBar,
    MenuBar,
    MenuItem,
    DockTab,
    DockTabActive,
    Splitter,
    Separator,
    Popup,
    Tooltip,
    Modal,
    Gizmo,
    ContentBrowser,
    TextPrimary,
    TextSecondary,
    TextCaption,
    Card,
    CardHover,
    TableHeader,
    TableRow,
    TableRowHover,
    TableRowSelected,
    SectionHeader,
    PropertyRow,
    SidebarItem,
    SidebarItemActive,
    WindowHeader,
    Checkbox,
    ToggleSwitch,
    Scrollbar,
    TreeItem,
    TreeItemSelected,
};

} // namespace WindEffects::Editor::UI
