#!/usr/bin/env python3
"""
Scan C++ codebase for AI-generated and unnatural comments.
"""
import os
import re
from pathlib import Path
from typing import List, Tuple

# Patterns that indicate AI-generated or unnatural comments
AI_COMMENT_PATTERNS = [
    # Conversational/instructional patterns
    r'// (This|This function|This method|This class|This code) (will|should|is intended to|is designed to)',
    r'// (We|Let us|Let\'s) (need to|can|should|will)',
    r'// Note that',
    r'// Please (note|ensure|remember)',
    r'// Make sure to',
    r'// Be careful to',
    r'// It is (important|recommended|suggested)',
    r'// (In order|In this case|For this purpose)',
    r'// (Here|Here we|Now we)',
    r'// (The|This) (implementation|approach|method|technique)',
    r'// (Essentially|Basically|Fundamentally)',
    r'// (Simply|Just|Only)',
    r'// (similar to|like|resembles|analogous to)',
    r'// (other software|other engines|similar systems|other platforms)',
    r'// (as seen in|as used in|as found in)',
    r'// (In contrast|Conversely|Similarly)',
    r'// (For example|For instance|Such as)',
    r'// (i\.e\.|e\.g\.)',
    r'// (Therefore|Thus|Hence|Consequently)',
    r'// (However|Nevertheless|Nonetheless)',
    r'// (Additionally|Furthermore|Moreover)',
    r'// (Finally|Lastly)',
    r'// (First|Second|Third|Next|Then)',
    r'// TODO.*\b(implement|add|create|make|fix|remove|delete|update|change|improve|optimize|refactor)\b',
    r'// FIXME.*\b(implement|add|create|make|fix|remove|delete|update|change|improve|optimize|refactor)\b',
    r'// HACK.*\b(implement|add|create|make|fix|remove|delete|update|change|improve|optimize|refactor)\b',
    # Meta commentary
    r'// (This is a|This creates|This sets up|This initializes|This returns)',
    r'// (We use|We are using|We will use)',
    r'// (The code|The implementation|The logic)',
    r'// (By using|Through the use of|Using)',
    r'// (In order to|To achieve this|For this reason)',
    r'// (This allows|This enables|This ensures)',
    r'// (This check|This validation|This verification)',
    r'// (This helps|This makes sure|This guarantees)',
    # Obvious narration
    r'// (Initialize|Create|Set|Get|Return|Call|Invoke|Check|Validate|Verify|Add|Remove|Delete|Update|Modify|Change) \w+',
    r'// (Increment|Decrement) \w+',
    r'// (Loop|Iterate) (through|over)',
    r'// (Check if|Verify if|Ensure that)',
    r'// (Return|Returns) \w+',
    r'// (Set|Setting) \w+ (to|as)',
    r'// (Get|Getting) \w+',
    # AI-style explanations
    r'// (This|The) (following|above|below)',
    r'// (works by|operates by|functions by)',
    r'// (is used to|is used for|is used in)',
    r'// (serves as|acts as|functions as)',
    r'// (provides|offers|gives)',
    r'// (handles|manages|deals with)',
    r'// (processes|processes the)',
    r'// (performs|executes|carries out)',
    r'// (contains|includes|consists of)',
    r'// (represents|stands for|symbolizes)',
    # References to external tools/agents
    r'// (AI|ChatGPT|Claude|Cursor|Copilot|agent|prompt)',
    r'// (generated by|created by|written by)',
    r'// (assistant|helper|tool)',
]

# Patterns to preserve (technical comments)
TECHNICAL_COMMENT_PATTERNS = [
    r'// (?:TODO|FIXME|HACK|XXX|NOTE):',  # Real technical TODOs
    r'// (?:WARNING|CAUTION|DANGER):',    # Important warnings
    r'// \b(?:NOTE|IMPORTANT)\b:',        # Important notes
    r'// (?:BUG|ISSUE):',                 # Bug tracking
    r'// (?:OPTIMIZE|PERF):',            # Performance notes
    r'// (?:THREA|SYNC|LOCK):',           # Threading/sync
    r'// (?:LIFETIME|OWNERSHIP):',        # Ownership/lifetime
    r'// (?:INVARIANT|ASSERTION):',      # Invariants
    r'// (?:WORKAROUND|HACK):\s+',        # Workarounds with reason
    r'// (?:API|PLATFORM|OS):\s+',        # Platform/API specific
    r'// (?:SERIALIZE|DESERIALIZE):',     # Serialization
    r'// (?:COMPAT|VERSION):\s+',         # Compatibility
    r'// (?:REQUIRE|CONSTRAINT):\s+',     # Constraints
    r'// \w+_h\b',                       # Header guards
    r'// Copyright',                     # Copyright
    r'// License',                       # License
    r'// SPDX',                          # SPDX identifiers
]

def is_technical_comment(comment: str) -> bool:
    """Check if a comment is a technical comment that should be preserved."""
    for pattern in TECHNICAL_COMMENT_PATTERNS:
        if re.search(pattern, comment, re.IGNORECASE):
            return True
    return False

def is_ai_comment(comment: str) -> bool:
    """Check if a comment appears to be AI-generated or unnatural."""
    if is_technical_comment(comment):
        return False
    
    for pattern in AI_COMMENT_PATTERNS:
        if re.search(pattern, comment, re.IGNORECASE):
            return True
    return False

def scan_file(filepath: Path) -> List[Tuple[int, str]]:
    """Scan a single file for AI-generated comments."""
    issues = []
    
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
    except Exception as e:
        return issues
    
    for i, line in enumerate(lines, 1):
        # Match single-line comments
        single_line_match = re.search(r'//(.*)$', line)
        if single_line_match:
            comment = single_line_match.group(1).strip()
            if comment and is_ai_comment(comment):
                issues.append((i, line.rstrip(), comment))
        
        # Match multi-line comments (simple detection)
        multi_line_start = re.search(r'/\*(.*)', line)
        if multi_line_start:
            content = multi_line_start.group(1).strip()
            if content and is_ai_comment(content):
                issues.append((i, line.rstrip(), content))
    
    return issues

def scan_directory(root_dir: Path) -> dict:
    """Scan all C++ files in a directory."""
    results = {}
    
    cpp_extensions = ['.cpp', '.h', '.hpp', '.cc', '.cxx', '.c']
    
    for filepath in root_dir.rglob('*'):
        if filepath.suffix in cpp_extensions:
            # Skip ThirdParty directories
            if 'ThirdParty' in str(filepath):
                continue
            
            issues = scan_file(filepath)
            if issues:
                results[str(filepath)] = issues
    
    return results

def main():
    """Main entry point."""
    script_dir = Path(__file__).parent
    root_dir = script_dir.parent / 'Engine' / 'Source'
    
    if not root_dir.exists():
        print(f"Error: Directory not found: {root_dir}")
        return
    
    print(f"Scanning C++ files in: {root_dir}")
    print("=" * 80)
    
    results = scan_directory(root_dir)
    
    total_files = len(results)
    total_issues = sum(len(issues) for issues in results.values())
    
    print(f"\nFound {total_issues} potential AI-generated comments in {total_files} files\n")
    
    for filepath, issues in sorted(results.items()):
        rel_path = Path(filepath).relative_to(root_dir.parent.parent)
        print(f"\n{rel_path} ({len(issues)} issue(s))")
        print("-" * 80)
        for line_num, line, comment in issues:
            print(f"  Line {line_num}: {line}")
            print(f"  Comment: {comment}")
            print()
    
    print("=" * 80)
    print(f"Total: {total_issues} issues in {total_files} files")

if __name__ == '__main__':
    main()
