# WindEffects editor viewport navigation settings
[ViewportNavigation]
NavigationPreset=UE5
MouseSensitivity=0.25
CameraAcceleration=1
CameraSmoothing=45
InvertX=false
InvertY=false
DefaultCameraSpeed=555
CameraSpeed=555
MaxBoostMultiplier=4
SlowMultiplier=0.25
OrbitAroundSelection=true
FocusOnSelection=true
ScrollWheelSpeedMultiplier=1
