# WindEffects editor viewport navigation settings
[ViewportNavigation]
NavigationPreset=Custom
MouseSensitivity=0.7228
CameraAcceleration=1
CameraSmoothing=2.7
InvertX=false
InvertY=false
DefaultCameraSpeed=1060.47
CameraSpeed=1060.47
MaxBoostMultiplier=4
SlowMultiplier=0.25
OrbitAroundSelection=true
FocusOnSelection=true
ScrollWheelSpeedMultiplier=1
